### PR TITLE
[DO NOT MERGE] Apparition – Initial Files

### PR DESCRIPTION
**Pull request by bcapps**
This is a WIP pull request so that @Twigz can see my progress so far. I've been working on getting in the initial character-building choices, and so far I've got my campaign, races, race images, magic types, skills, stats, and calendar added in the JSON. I also added my cases to the RaceType enum in code and the resulting changes from those. 

I still have yet to replace the spells and gods and then I will be adding items.

@Twigz for merging purposes, it'd be great to have the capability to add my own, separate JSON files sooner than later so I don't have to overwrite the OG ones. Additionally, it'd be great if less was hardcoded, so things like starting stats, skills, spells, and even items and gold could all be right in the Race JSON, for example, and then there'd be less to modify in the code itself.

### CODE REVIEW

**Comment by Twigz** [comment]
That would be great. Unfortunately I'm behind on this stuff due to NC, but if you want to take a crack at it feel free.

**Comment by bcapps** [comment]
Cool, I just got the race attributes into the JSON and working. Haven't updated the tests yet, but the app works.

**Comment by bcapps** [comment]
Also removed hardcoding for gods and magic types by adding the attributes to the JSON. Still haven't updated any tests.

**Comment by Twigz** [comment]
I wouldn't worry about the tests too much. They're a bit out of date.

**Pull request closed without merging**
